### ISSUE TITLE
Tidymodels Interface

### ISSUE THREAD

**Issue by lorenzwalthert** [nicolagnecco/erf#5]
Hi @nicolagnecco, cool Package. Hope everything is well with you. Just wanted to bring to your attention that there is the [{hardhat}](https://hardhat.tidymodels.org/) package from RStudio that you can use to build a tidymodels compatible package and then benefit from all their adjective to packages and eco system, eg for model tuning. For example, It helps you creating predict and fit functions for matrix, receive and formula interfaces.

**Comment by nicolagnecco** [comment]
Hi @lorenzwalthert, thanks! I will have a look into [{hardhat}](https://hardhat.tidymodels.org/), looks very useful.
