### ISSUE TITLE
Is there a version of ERF available in languages other than R (e.g., C++ or Python)?

### ISSUE THREAD

**Issue by William-M-Ricardo** [nicolagnecco/erf#7]
Hello,

Thank you for your great work on ERF! I find it very useful and appreciate the effort that has gone into this project.

I was wondering if there are any versions of ERF available in other programming languages, such as C++ or Python. If not, are there any plans to extend support to these languages in the future?

This would be very helpful for integrating ERF into other platforms and workflows that rely on these languages.

Looking forward to your response!

Best regards,  
William

**Comment by nicolagnecco** [comment]
Hi William,

Thank you for your message. 
Currently, there is no plan to extend ERF to other programming languages. However, I am happy to provide support if someone is willing to undertake this endeavor.
