### ISSUE TITLE
Should I divide returns to positive and negative and estimate two models?

### ISSUE THREAD

**Issue by MislavSag** [nicolagnecco/erf#9]
Hello,

Congrats on developing this great package. If I want to model stock returns with `erf`, should I use positive and negative return separatly or I should use all return as intput (X, Y). My experiment show more reasonable results for separate positive and negative returns estimaition.

**Comment by nicolagnecco** [comment]
Hi,

Thanks for your message. Extreme quantile estimation (like ERF) focuses on one tail at a time. For example, it is usual to concentrate on significant losses (large negative returns) in financial applications. For this reason, I suggest modeling positive and negative returns as two distinct problems.

Let me know if this answers your question.

Best wishes,
Nicola

**Comment by MislavSag** [comment]
I needed confirmation. Thanks.
